# fly.toml app configuration file generated for stack-overflow-relay on 2023-07-10T17:23:38-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "stack-overflow-relay"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
dockerfile = "Dockerfile"

[processes]
app = "/bin/sh -c '/app/diesel migration run && /app/stack-overflow-relay'"

[experimental]
auto_rollback = true

[[services]]
internal_port = 8080
processes = ["app"]
protocol = "tcp"

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
