use crate::{
    domain::Notification,
    stack_overflow::{AccessToken, AccountId},
};
use diesel::prelude::*;
use futures::{
    channel::{mpsc, oneshot},
    SinkExt, StreamExt,
};
use snafu::{ResultExt, Snafu};

mod models;
mod schema;

pub struct Db {
    conn: diesel::PgConnection,
}

impl Db {
    pub fn new(conn: diesel::PgConnection) -> Self {
        Self { conn }
    }
}

impl Db {
    fn register(&self, account_id: AccountId, access_token: AccessToken) -> Result<()> {
        use models::Registration;
        use schema::registrations::dsl;

        let Self { conn } = self;

        let registration = Registration {
            account_id: account_id.0,
            access_token: access_token.0,
        };

        diesel::insert_into(dsl::registrations)
            .values(&registration)
            .on_conflict(dsl::account_id)
            .do_update()
            .set(dsl::access_token.eq(dsl::access_token))
            .execute(conn)
            .context(UnableToInsertRegistration)?;

        Ok(())
    }

    fn add_new_notifications(
        &self,
        notifications: Vec<(AccountId, String)>,
    ) -> Result<Vec<Notification>> {
        use models::NewNotification;
        use schema::notifications::dsl;

        let Self { conn } = self;

        let notifications: Vec<_> = notifications
            .into_iter()
            .map(|(AccountId(account_id), text)| NewNotification { account_id, text })
            .collect();

        let db_notifications = diesel::insert_into(dsl::notifications)
            .values(notifications)
            .on_conflict((dsl::account_id, dsl::text))
            .do_nothing()
            .returning((dsl::id, dsl::account_id, dsl::text))
            .get_results::<models::Notification>(conn)
            .context(UnableToInsertNotification)?;

        Ok(db_notifications.into_iter().map(Into::into).collect())
    }
}

#[derive(Debug, Snafu)]
pub enum Error {
    UnableToInsertRegistration { source: diesel::result::Error },

    UnableToInsertNotification { source: diesel::result::Error },
}

type Result<T, E = Error> = std::result::Result<T, E>;

// Can this be auto-generated by a proc-macro?
// https://draft.ryhl.io/blog/actors-with-tokio/

pub fn spawn(this: Db) -> (DbHandle, tokio::task::JoinHandle<()>) {
    let (tx, rx) = mpsc::channel(10);
    let child = tokio::spawn(db_task(this, rx));
    (DbHandle(tx), child)
}

#[derive(Debug, Clone)]
pub struct DbHandle(mpsc::Sender<DbCommand>);

impl DbHandle {
    pub async fn register(&mut self, a: AccountId, b: AccessToken) -> Result<()> {
        let (tx, rx) = oneshot::channel();

        // Ignore send errors. If this send fails, so does the
        // rx.await below. There's no reason to check for the
        // same failure twice.
        let _ = self.0.send(DbCommand::Register(tx, a, b)).await;
        rx.await.expect("Actor error - task gone")
    }

    pub async fn add_new_notifications(
        &mut self,
        a: Vec<(AccountId, String)>,
    ) -> Result<Vec<Notification>> {
        let (tx, rx) = oneshot::channel();

        // Ignore send errors. If this send fails, so does the
        // rx.await below. There's no reason to check for the
        // same failure twice.
        let _ = self.0.send(DbCommand::AddNewNotifications(tx, a)).await;
        rx.await.expect("Actor error - task gone")
    }
}

#[derive(Debug)]
enum DbCommand {
    Register(oneshot::Sender<Result<()>>, AccountId, AccessToken),

    AddNewNotifications(
        oneshot::Sender<Result<Vec<Notification>>>,
        Vec<(AccountId, String)>,
    ),
}

async fn db_task(#[allow(unused_mut)] mut this: Db, mut rx: mpsc::Receiver<DbCommand>) {
    while let Some(cmd) = rx.next().await {
        match cmd {
            DbCommand::Register(__r, a, b) => {
                // Macro: block_in_place vs nothing vs spawn_blocking
                // TODO: This should be spawn-blocking
                let retval = tokio::task::block_in_place(|| this.register(a, b));

                // If we couldn't respond, that's OK
                let _ = __r.send(retval);
            }

            DbCommand::AddNewNotifications(__r, a) => {
                // Macro: block_in_place vs nothing vs spawn_blocking
                // TODO: This should be spawn-blocking
                let retval = tokio::task::block_in_place(|| this.add_new_notifications(a));

                // If we couldn't respond, that's OK
                let _ = __r.send(retval);
            }
        }
    }
}

//
