use crate::{
    flow::NotifyFlow,
    stack_overflow::{self, AccessToken, AccountId, UnreadParams},
    GlobalConfig, GlobalStackOverflowConfig,
};
use futures::{
    channel::{mpsc, oneshot},
    future::RemoteHandle,
    FutureExt, SinkExt, StreamExt,
};
use std::collections::HashMap;
use tokio::task::JoinHandle;
use tracing::{trace, trace_span, warn, Instrument};

#[derive(Debug)]
pub struct PollSpawner {
    config: GlobalConfig,
    so_config: GlobalStackOverflowConfig,
    pollers: HashMap<AccountId, RemoteHandle<()>>,
    flow: NotifyFlow,
}

// Not part of actor API
impl PollSpawner {
    pub fn new(
        config: GlobalConfig,
        so_config: GlobalStackOverflowConfig,
        flow: NotifyFlow,
    ) -> Self {
        Self {
            config,
            so_config,
            pollers: Default::default(),
            flow,
        }
    }
}

// Actor API
impl PollSpawner {
    fn start_polling(&mut self, account_id: AccountId, access_token: AccessToken) {
        let s = trace_span!("start_polling", account_id = account_id.0);
        let _s = s.enter();
        trace!("Starting new polling task");

        let Self {
            config,
            so_config,
            pollers,
            flow,
        } = self;

        // `remote_handle` should kill the future when the
        // `handle` is dropped, which will happen if we replace
        // the hashmap entry for the same account.
        let (work, handle) =
            poll_one_account(config, so_config, account_id, access_token, flow.clone())
                .remote_handle();
        tokio::spawn(work);
        let old_work = pollers.insert(account_id, handle);

        if let Some(old_work) = old_work {
            if old_work.now_or_never().is_none() {
                warn!("Second worker started");
            }
        }
    }
}

async fn poll_one_account(
    config: GlobalConfig,
    so_config: GlobalStackOverflowConfig,
    account_id: AccountId,
    access_token: AccessToken,
    mut flow: NotifyFlow,
) {
    let s = trace_span!("poll_one_account", account_id = account_id.0);
    async {
        trace!("Starting polling");

        let params = UnreadParams {
            key: &config.stack_overflow_client_key,
            site: "stackoverflow",
            access_token: &access_token,
            filter: "default",
        };

        let r = stack_overflow::unread_notifications(so_config, &params).await;
        dbg!(&r);

        let r = r.expect("TODO").into_result().expect("TODO");
        let r = r.items.into_iter().map(|n| (account_id, n.body)).collect();

        flow.notify(r).await.expect("TODO");
    }
    .instrument(s)
    .await
}

// Can this be auto-generated by a proc-macro?
// https://draft.ryhl.io/blog/actors-with-tokio/

pub fn spawn(this: PollSpawner) -> (PollSpawnerHandle, JoinHandle<()>) {
    let (tx, rx) = mpsc::channel(10);
    let child = tokio::spawn(poll_spawner_task(this, rx));
    (PollSpawnerHandle(tx), child)
}

#[derive(Debug, Clone)]
pub struct PollSpawnerHandle(mpsc::Sender<PollSpawnerCommand>);

impl PollSpawnerHandle {
    pub async fn start_polling(&mut self, a: AccountId, b: AccessToken) {
        let (tx, rx) = oneshot::channel();

        // Ignore send errors. If this send fails, so does the
        // rx.await below. There's no reason to check for the
        // same failure twice.
        let _ = self.0.send(PollSpawnerCommand::Register(tx, a, b)).await;
        rx.await.expect("TODO")
    }
}

#[derive(Debug)]
enum PollSpawnerCommand {
    Register(oneshot::Sender<()>, AccountId, AccessToken),
}

async fn poll_spawner_task(mut this: PollSpawner, mut rx: mpsc::Receiver<PollSpawnerCommand>) {
    while let Some(cmd) = rx.next().await {
        match cmd {
            PollSpawnerCommand::Register(__r, a, b) => {
                let retval = this.start_polling(a, b);
                // If we couldn't respond, that's OK
                let _ = __r.send(retval);
            }
        }
    }
}

//
