name: "Fly Deploy"
on:
  push:
    branches: ['fly']

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
      name: Deploy application
      runs-on: ubuntu-latest
      environment: deploy
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only --build-arg SOURCE_VERSION="${{ github.sha }}"
